
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/server",
    "crates/client",
    "crates/api",
    "crates/iperf3-cli"
]
