/* Generated by this command line `bindgen --generate functions,types --allowlist-function 'iperf_.*' --allowlist-type 'iperf_.*' --blocklist-function 'iperf_(send|recv|get_test_outfile)' --blocklist-type '(FILE|fd_set|__sbuf|__sFILE|__sFILEX)' extern/iperf/src/iperf_api.h -o src/iperf_bindings.rs` */
/* And then hand edited to remove unnecessary crap */
#![allow(non_camel_case_types, dead_code)]

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iperf_test {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iperf_stream_result {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iperf_interval_results {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iperf_stream {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iperf_time {
    _unused: [u8; 0],
}
pub type iperf_size_t = u64;
extern "C" {
    pub fn iperf_get_verbose(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_control_socket(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_omit(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_duration(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_role(ipt: *mut iperf_test) -> ::std::os::raw::c_char;
}
extern "C" {
    pub fn iperf_get_test_reverse(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_blksize(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_rate(ipt: *mut iperf_test) -> u64;
}
extern "C" {
    pub fn iperf_get_test_pacing_timer(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_bytes(ipt: *mut iperf_test) -> u64;
}
extern "C" {
    pub fn iperf_get_test_blocks(ipt: *mut iperf_test) -> u64;
}
extern "C" {
    pub fn iperf_get_test_burst(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_socket_bufsize(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_reporter_interval(ipt: *mut iperf_test) -> f64;
}
extern "C" {
    pub fn iperf_get_test_stats_interval(ipt: *mut iperf_test) -> f64;
}
extern "C" {
    pub fn iperf_get_test_num_streams(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_repeating_payload(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_timestamps(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_timestamp_format(ipt: *mut iperf_test) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn iperf_get_test_server_port(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_server_hostname(ipt: *mut iperf_test) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn iperf_get_test_template(ipt: *mut iperf_test) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn iperf_get_test_protocol_id(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_json_output(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_json_output_string(ipt: *mut iperf_test) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn iperf_get_test_zerocopy(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_get_server_output(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_unit_format(ipt: *mut iperf_test) -> ::std::os::raw::c_char;
}
extern "C" {
    pub fn iperf_get_test_bind_address(ipt: *mut iperf_test) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn iperf_get_test_udp_counters_64bit(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_one_off(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_tos(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_extra_data(ipt: *mut iperf_test) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn iperf_get_iperf_version() -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn iperf_get_test_no_delay(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_connect_timeout(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_dont_fragment(ipt: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_get_test_congestion_control(ipt: *mut iperf_test) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn iperf_set_verbose(ipt: *mut iperf_test, verbose: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_control_socket(ipt: *mut iperf_test, ctrl_sck: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_omit(ipt: *mut iperf_test, omit: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_duration(ipt: *mut iperf_test, duration: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_reporter_interval(ipt: *mut iperf_test, reporter_interval: f64);
}
extern "C" {
    pub fn iperf_set_test_stats_interval(ipt: *mut iperf_test, stats_interval: f64);
}
extern "C" {
    pub fn iperf_set_test_state(ipt: *mut iperf_test, state: ::std::os::raw::c_schar);
}
extern "C" {
    pub fn iperf_set_test_blksize(ipt: *mut iperf_test, blksize: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_logfile(ipt: *mut iperf_test, logfile: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn iperf_set_test_rate(ipt: *mut iperf_test, rate: u64);
}
extern "C" {
    pub fn iperf_set_test_pacing_timer(ipt: *mut iperf_test, pacing_timer: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_bytes(ipt: *mut iperf_test, bytes: u64);
}
extern "C" {
    pub fn iperf_set_test_blocks(ipt: *mut iperf_test, blocks: u64);
}
extern "C" {
    pub fn iperf_set_test_burst(ipt: *mut iperf_test, burst: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_server_port(ipt: *mut iperf_test, server_port: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_socket_bufsize(
        ipt: *mut iperf_test,
        socket_bufsize: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn iperf_set_test_num_streams(ipt: *mut iperf_test, num_streams: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_repeating_payload(
        ipt: *mut iperf_test,
        repeating_payload: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn iperf_set_test_timestamps(ipt: *mut iperf_test, timestamps: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_timestamp_format(
        arg1: *mut iperf_test,
        tf: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn iperf_set_test_role(ipt: *mut iperf_test, role: ::std::os::raw::c_char);
}
extern "C" {
    pub fn iperf_set_test_server_hostname(
        ipt: *mut iperf_test,
        server_hostname: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn iperf_set_test_template(
        ipt: *mut iperf_test,
        tmp_template: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn iperf_set_test_reverse(ipt: *mut iperf_test, reverse: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_json_output(ipt: *mut iperf_test, json_output: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_has_zerocopy() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_set_test_zerocopy(ipt: *mut iperf_test, zerocopy: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_get_server_output(
        ipt: *mut iperf_test,
        get_server_output: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn iperf_set_test_unit_format(ipt: *mut iperf_test, unit_format: ::std::os::raw::c_char);
}
extern "C" {
    pub fn iperf_set_test_bind_address(
        ipt: *mut iperf_test,
        bind_address: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn iperf_set_test_udp_counters_64bit(
        ipt: *mut iperf_test,
        udp_counters_64bit: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn iperf_set_test_one_off(ipt: *mut iperf_test, one_off: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_tos(ipt: *mut iperf_test, tos: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_extra_data(ipt: *mut iperf_test, dat: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn iperf_set_test_bidirectional(ipt: *mut iperf_test, bidirectional: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_no_delay(ipt: *mut iperf_test, no_delay: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_dont_fragment(ipt: *mut iperf_test, dont_fragment: ::std::os::raw::c_int);
}
extern "C" {
    pub fn iperf_set_test_congestion_control(ipt: *mut iperf_test, cc: *mut ::std::os::raw::c_char);
}
extern "C" {
    pub fn iperf_set_test_client_username(
        ipt: *mut iperf_test,
        client_username: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn iperf_set_test_client_password(
        ipt: *mut iperf_test,
        client_password: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn iperf_set_test_client_rsa_pubkey(
        ipt: *mut iperf_test,
        client_rsa_pubkey_base64: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn iperf_set_test_server_authorized_users(
        ipt: *mut iperf_test,
        server_authorized_users: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn iperf_set_test_server_skew_threshold(
        ipt: *mut iperf_test,
        server_skew_threshold: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn iperf_set_test_server_rsa_privkey(
        ipt: *mut iperf_test,
        server_rsa_privkey_base64: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn iperf_set_test_connect_timeout(ipt: *mut iperf_test, ct: ::std::os::raw::c_int);
}
extern "C" {
    #[doc = " exchange_parameters - handles the param_Exchange part for client"]
    #[doc = ""]
    pub fn iperf_exchange_parameters(test: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " iperf_stats_callback -- handles the statistic gathering"]
    #[doc = ""]
    pub fn iperf_stats_callback(test: *mut iperf_test);
}
extern "C" {
    #[doc = " iperf_reporter_callback -- handles the report printing"]
    #[doc = ""]
    pub fn iperf_reporter_callback(test: *mut iperf_test);
}
extern "C" {
    #[doc = " iperf_new_test -- return a new iperf_test with default values"]
    #[doc = ""]
    #[doc = " returns NULL on failure"]
    #[doc = ""]
    pub fn iperf_new_test() -> *mut iperf_test;
}
extern "C" {
    pub fn iperf_defaults(testp: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " iperf_free_test -- free resources used by test, calls iperf_free_stream to"]
    #[doc = " free streams"]
    #[doc = ""]
    pub fn iperf_free_test(testp: *mut iperf_test);
}
extern "C" {
    #[doc = " iperf_new_stream -- return a net iperf_stream with default values"]
    #[doc = ""]
    #[doc = " returns NULL on failure"]
    #[doc = ""]
    pub fn iperf_new_stream(
        arg1: *mut iperf_test,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> *mut iperf_stream;
}
extern "C" {
    #[doc = " iperf_add_stream -- add a stream to a test"]
    #[doc = ""]
    pub fn iperf_add_stream(test: *mut iperf_test, stream: *mut iperf_stream);
}
extern "C" {
    #[doc = " iperf_init_stream -- init resources associated with test"]
    #[doc = ""]
    pub fn iperf_init_stream(
        arg1: *mut iperf_stream,
        arg2: *mut iperf_test,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " iperf_free_stream -- free resources associated with test"]
    #[doc = ""]
    pub fn iperf_free_stream(sp: *mut iperf_stream);
}
extern "C" {
    pub fn iperf_set_send_state(
        test: *mut iperf_test,
        state: ::std::os::raw::c_schar,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_check_throttle(sp: *mut iperf_stream, nowP: *mut iperf_time);
}
extern "C" {
    pub fn iperf_catch_sigend(
        handler: ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>,
    );
}
extern "C" {
    pub fn iperf_got_sigend(test: *mut iperf_test);
}
extern "C" {
    pub fn iperf_exchange_results(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_init_test(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_create_send_timers(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_parse_arguments(
        arg1: *mut iperf_test,
        arg2: ::std::os::raw::c_int,
        arg3: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_open_logfile(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_reset_test(arg1: *mut iperf_test);
}
extern "C" {
    pub fn iperf_reset_stats(test: *mut iperf_test);
}
extern "C" {
    pub fn iperf_on_new_stream(arg1: *mut iperf_stream);
}
extern "C" {
    pub fn iperf_on_test_start(arg1: *mut iperf_test);
}
extern "C" {
    pub fn iperf_on_connect(arg1: *mut iperf_test);
}
extern "C" {
    pub fn iperf_on_test_finish(arg1: *mut iperf_test);
}
extern "C" {
    pub fn iperf_run_client(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_connect(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_create_streams(
        arg1: *mut iperf_test,
        sender: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_handle_message_client(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_client_end(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_run_server(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_server_listen(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_accept(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_handle_message_server(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_create_pidfile(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_delete_pidfile(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_check_total_rate(arg1: *mut iperf_test, arg2: iperf_size_t);
}
extern "C" {
    pub fn iperf_json_start(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_json_finish(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_setaffinity(
        arg1: *mut iperf_test,
        affinity: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_clearaffinity(arg1: *mut iperf_test) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_printf(
        test: *mut iperf_test,
        format: *const ::std::os::raw::c_char,
        ...
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn iperf_err(test: *mut iperf_test, format: *const ::std::os::raw::c_char, ...);
}
extern "C" {
    pub fn iperf_errexit(test: *mut iperf_test, format: *const ::std::os::raw::c_char, ...);
}
extern "C" {
    pub fn iperf_strerror(arg1: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char;
}
