name: CD
on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: ~/.fly/bin/fly deploy --local-only
