name: CD

on:
  push:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: ~/.fly/bin/fly deploy --local-only
