name: check

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: check
    runs-on: self-hosted

    if: ${{github.event.label == 'CI'}}
    steps:
    - uses: actions/checkout@v3
    # - name: Cache objects
    #   uses: actions/cache@v3
    #   with:
    #     key: target-dir
    #     path: |
    #       ./target
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
