name: check

on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - dev
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: check
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        sparse-checkout: |
          crates
          .sqlx
          .cargo
          .git
          .github
          Cargo.toml
          fly.toml
          Dockerfile.server

    # Create a pull request if not on one
    - run: gh pr create -B main -f -l CI
      continue-on-error: true
      if:  contains(github.ref, 'dev') && contains(!github.event_name, 'pull_request')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Deploy to Fly
      # only run from main
      if:  contains(github.ref, 'main')
      run: ~/.fly/bin/fly deploy --local-only
