name: CI

on:
  push:
    branches: 
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  pull_request:
    name: Create PR if not exists
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    # Create a pull request if not on one
    - run: gh pr create -B main -f -l CI
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check:
    name: check
    runs-on: self-hosted
    needs: pull_request

    steps:
    - uses: actions/checkout@v3

    - name: Get my own object cache
      continue-on-error: true
      run: rsync -a --link-dest=../ ../_obj_cache/ target/
          
    - name: Check
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Sync back to it
      run:
        rsync -a --delete --link-dest=../ target/ ../_obj_cache/
    
  check_merge:
    name: yolo merge it (if tests pass)
    runs-on: self-hosted
    needs: check
    if: contains(github.ref, 'dev')
    steps:
    - uses: actions/checkout@v3
    - run: gh pr merge --merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
