name: CI_CD

on:
  push:
    branches: 
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:

  check:
    name: check
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - run: mkdir target/
      continue-on-error: true

    - run: mkdir -p ../_obj_cache/
      continue-on-error: true

    - name: Get my own object cache
      continue-on-error: true
      run: |
        cp -lr ../_obj_cache/* target/
          
    - name: Check
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Sync back to it
      run:
        rsync -a --delete --link-dest=../ target/* ../_obj_cache/
    
  pull_request:
    name: Create PR if not exists
    runs-on: self-hosted
    needs: check
    steps:
    - uses: actions/checkout@v3

    # Create a pull request if not on one
    - run: gh pr create -B main -f -l CI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_merge:
    name: yolo merge it
    runs-on: self-hosted
    needs: pull_request
    if: contains(github.ref, 'dev')
    steps:
    - uses: actions/checkout@v3
    - run: gh pr merge --merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to Fly.io
    runs-on: self-hosted
    needs: check_merge
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'
    - run: ~/.fly/bin/fly deploy --local-only
