name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: deploy
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: deploy via flyctl
      run: ~/.fly/bin/fly deploy --local-only
